import Foundation
import MPPEVM

/// Persistence for the server-held **access keys** a subscription delegates to.
///
/// At challenge time the server issues an access-key *address* in the 402's
/// `methodDetails.accessKey`; the payer signs a ``TempoKeyAuthorization`` delegating recurring
/// `transferWithMemo` to it. The server must therefore generate and keep the access key's
/// **private key** so the renewal engine can later sign the recurring charge with it. This is
/// that store, keyed by the subscription's `lookupKey` (one access key per active subscription,
/// matching the reference SDK's `store.getAccessKey(lookupKey)`).
///
/// - Important: this holds spendable **secp256k1 private keys at rest**. ``InMemoryAccessKeyStore``
///   keeps them in process memory and is for a single process and tests **only**; a real deployment
///   backs this seam with secure storage (an OS keychain or KMS-backed store) that returns the key
///   for the renewal FFI to sign with and zeroize. Never log key material. NOTE: the seam returns
///   raw key bytes because the renewal path signs with them; a fully non-exporting HSM (which never
///   releases the key) would instead need a signing-delegation seam, a follow-up beyond this store.
public protocol AccessKeyStore: Sendable {
    /// Returns the access-key address to embed in a subscription challenge for `lookupKey`,
    /// generating and storing a fresh keypair on first use and returning the existing address
    /// thereafter (idempotent per `lookupKey`).
    func provision(forLookupKey lookupKey: String) async throws -> EthereumAddress

    /// The stored access-key private key for `lookupKey` (for renewal signing), or `nil` if the
    /// key has not been provisioned.
    func privateKey(forLookupKey lookupKey: String) async -> Data?
}

/// A reason an ``AccessKeyStore`` operation failed.
public enum AccessKeyStoreError: Error, Sendable, Hashable {
    /// The generated bytes were not a valid secp256k1 private key, or no address could be
    /// derived from them (astronomically unlikely for a random key; surfaced, never ignored).
    case keyDerivationFailed
}

/// An in-memory ``AccessKeyStore`` backed by an actor: suitable for a single process and tests.
/// The actor serializes ``provision(forLookupKey:)`` so two concurrent first-uses of the same
/// `lookupKey` cannot mint two keys. NOT for production (keys live in process memory); back the
/// seam with secure storage there.
public actor InMemoryAccessKeyStore: AccessKeyStore {
    private struct Entry {
        let privateKey: Data
        let address: EthereumAddress
    }

    private var entries: [String: Entry] = [:]
    private let keyGenerator: @Sendable () -> Data

    /// Creates the store.
    /// - Parameter keyGenerator: produces a 32-byte secp256k1 private key; defaults to 32
    ///   system-RNG random bytes (`UInt8.random`, the same source the crypto layer seeds with).
    ///   Injectable so tests can provision deterministic keys.
    public init(
        keyGenerator: @escaping @Sendable () -> Data = {
            Data((0 ..< 32).map { _ in UInt8.random(in: .min ... .max) })
        }
    ) {
        self.keyGenerator = keyGenerator
    }

    public func provision(forLookupKey lookupKey: String) throws -> EthereumAddress {
        if let existing = entries[lookupKey] { return existing.address }
        let privateKey = keyGenerator()
        let signer: Secp256k1Signer
        do {
            signer = try Secp256k1Signer(privateKey: privateKey)
        } catch {
            throw AccessKeyStoreError.keyDerivationFailed
        }
        guard let address = EthereumAddress(uncompressedPublicKey: signer.publicKey) else {
            throw AccessKeyStoreError.keyDerivationFailed
        }
        entries[lookupKey] = Entry(privateKey: privateKey, address: address)
        return address
    }

    public func privateKey(forLookupKey lookupKey: String) -> Data? {
        entries[lookupKey]?.privateKey
    }
}
